SocketManager/urls.py
from django.contrib import admin
from django.urls import path

from socket_manager.views.index import index
from socket_manager.views.add import add

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('add/', add, name='add')
]

socket_manager/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Host(models.Model):
    id = models.IntegerField(primary_key=True)
    hostname = models.CharField(max_length=128)
    ip = models.CharField(max_length=32)

    class Meta:
        managed = False
        db_table = 'host'

    def __str__(self):
        return '{} | {} '.format(self.hostname, self.ip)

class Socket(models.Model):
    id = models.IntegerField(primary_key=True)
    id_host = models.ForeignKey(Host, models.DO_NOTHING, db_column='id_host')
    port = models.IntegerField(blank=True, null=True)
    socket_name = models.CharField(max_length=128)
    socket_description = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'socket'

    def __str__(self):
        return '{} | {}:{} '.format(self.socket_name, Host.objects.get(id=self.id_host.id).ip, self.port)

socket_manager/forms/hostForm.py
from django import forms


class HostForm(forms.Form):
    hostname = forms.CharField()
    ip = forms.CharField()

    hostname.widget.attrs.update({'class': 'form-control'})
    ip.widget.attrs.update({'class': 'form-control'})

socket_manager/forms/socketForm.py
from django import forms


class SocketForm(forms.Form):

    port = forms.IntegerField()
    socket_name = forms.CharField()
    socket_description = forms.CharField()

    port.widget.attrs.update({'class': 'form-control'})
    socket_name.widget.attrs.update({'class': 'form-control'})
    socket_description.widget.attrs.update({'class': 'form-control'})

socket_manager/views/add.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from socket_manager.forms.hostForm import HostForm
from socket_manager.forms.socketForm import SocketForm
from socket_manager.models import Host, Socket


@login_required(login_url='/admin/login?next=/')
def add(request):
    if request.method == "POST":
        post = request.POST

        if post['form_type'] == "host-form":
            Host(hostname=post['hostname'], ip=post['ip']).save()
        elif post['form_type'] == "socket-form":
            Socket(id_host=Host.objects.get(id=post['selector']), socket_name=post['socket_name'], socket_description=post['socket_description'], port=post['port']).save()

    host_form = HostForm()
    socket_form = SocketForm()
    hosts = Host.objects.all()
    return render(request, 'add.html', {'host': host_form, 'socket': socket_form, 'hosts': hosts })

socket_manager/views/index.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from socket_manager.models import Host, Socket

@login_required(login_url='/admin/login?next=/')
def index(request):
    hosts = Host.objects.all()
    sockets = Socket.objects.all()

    return render(request, 'index.html', {'hosts': hosts, 'sockets': sockets})

socket_manager/views/views.py
from django.shortcuts import render

# Create your views here.

socket_manager/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Index{% endblock %}

{% block content %}
    <div class="min-vh-100">
         <div class="container" style="margin-top: 40px;">
            <div>
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item" role="presentation"><a class="nav-link active" role="tab" data-bs-toggle="tab"
                                                                href="#tab-1">Socket</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-bs-toggle="tab"
                                                                href="#tab-2">Host</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="tab-1">
                        <form style="margin-top: 32px;" id="socket-form" method="post">
                            {% csrf_token %}
                            <h1 style="margin-left: 32px;font-size: 48px;">Create Host</h1>
                            <div class="container" style="margin-top: 16px;">
                                <div class="row">
                                    <div class="col-md-3"><label for="id_port" class="form-label">Port</label>{{ socket.port }}</div>
                                    <div class="col-md-3"><label for="id_socket_name" class="form-label">Name</label>{{ socket.socket_name }}</div>
                                    <div class="col-md-3"><label for="id_socket_description" class="form-label">Description</label>{{ socket.socket_description }}</div>
                                    <div class="col-md-3">
                                        <select style="margin-top: 16px;" id="selector" name="selector">
                                            {% for obj in hosts %}
                                                <option value="{{ obj.id }}" class="form-control">{{ obj.hostname }}</option>
                                            {%  endfor %}
                                        </select>
                                    </div>
                                    <div class="col-md-3"><input type="hidden" id="form_type" name="form_type" value="socket-form"></div>
                                </div>
                            </div>
                        </form>
                        <button style="margin-left: 32px; margin-top: 32px;" class="btn btn-primary" type="submit" form="socket-form" value="Submit">Submit</button>
                    </div>
                    <div class="tab-pane" role="tabpanel" id="tab-2">
                        <form style="margin-top: 32px;" id="host-form" method="post">
                            {% csrf_token %}
                            <h1 style="margin-left: 32px;font-size: 48px;">Create Host</h1>
                            <div class="container" style="margin-top: 16px;">
                                <div class="row">
                                    <div class="col-md-3"><label for="id_hostname" class="form-label">Hostname</label>{{ host.hostname }}</div>
                                    <div class="col-md-3"><label for="id_ip" class="form-label">IP</label>{{ host.ip }}</div>
                                    <div class="col-md-3"><input type="hidden" id="form_type" name="form_type" value="host-form"></div>
                                </div>
                            </div>
                        </form>
                        <button style="margin-left: 32px; margin-top: 32px;" class="btn btn-primary" type="submit" form="host-form" value="Submit">Submit</button>
                    </div>
                </div>
            </div>
         </div>
    </div>
{% endblock %}

socket_manager/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<link rel="manifest" href="{% static 'manifest.json' %}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Socket Manager</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&amp;display=swap">
    <link rel="stylesheet" href="{% static 'css/Navbar-Right-Links-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/shadow.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

</head>
<body>
<header>
    <nav class="navbar navbar-dark navbar-expand-md bg-dark py-3">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'index' %}"><span
                class="bs-icon-sm bs-icon-rounded bs-icon-primary d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plugin" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a7 7 0 1 1 2.898 5.673c-.167-.121-.216-.406-.002-.62l1.8-1.8a3.5 3.5 0 0 0 4.572-.328l1.414-1.415a.5.5 0 0 0 0-.707l-.707-.707 1.559-1.563a.5.5 0 1 0-.708-.706l-1.559 1.562-1.414-1.414 1.56-1.562a.5.5 0 1 0-.707-.706l-1.56 1.56-.707-.706a.5.5 0 0 0-.707 0L5.318 5.975a3.5 3.5 0 0 0-.328 4.571l-1.8 1.8c-.58.58-.62 1.6.121 2.137A8 8 0 1 0 0 8a.5.5 0 0 0 1 0Z"/>
</svg></span><span>Socket Manger V1</span></a>
            <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-5"><span
                    class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-5">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="https://home.enzo-laurence.tech">Home</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'index' %}">Index</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                    {% if request.user.is_authenticated == False %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:login' %}?next={% url 'index' %}">Login</a></li>
                    {% else%}
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:logout' %}?next={% url 'index' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main>
    {% block content %}
    {% endblock %}
</main>
<footer>
    <div class="fixed-bottom" style="margin-bottom: 16px;">
        <div class="btn-group float-xl-end" role="group">
            <a href="{% url 'add' %}">
                <button class="btn btn-primary" type="button"
                        style="margin-right: 8px;border-radius: 50%;width: 64px;height: 64px;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor"
                         viewBox="0 0 16 16"
                         class="bi bi-plus" style="width: 32px;height: 32px;">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                    </svg>
                </button>
            </a>
        </div>
    </div>
</footer>
</body>
</html>

socket_manager/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Index{% endblock %}

{% block content %}
    <div class="min-vh-100">
         <div class="container" style="margin-top: 40px;">
            <div>
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item" role="presentation"><a class="nav-link active" role="tab" data-bs-toggle="tab"
                                                                href="#tab-1">Socket</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" role="tab" data-bs-toggle="tab"
                                                                href="#tab-2">Host</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" role="tabpanel" id="tab-1">
                        <div class="table-responsive" style="margin-top: 16px;">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>IP</th>
                                    <th>Port</th>
                                    <th>Nom</th>
                                    <th>Description</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for obj in sockets %}
                                    <tr>
                                        <td>{{ obj.id_host }}</td>
                                        <td>{{ obj.port }}</td>
                                        <td>{{ obj.socket_name }}</td>
                                        <td>{{ obj.socket_description }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane" role="tabpanel" id="tab-2">
                        <div class="table-responsive" style="margin-top: 16px;">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Hostname</th>
                                    <th>Port</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for obj in hosts %}
                                    <tr>
                                        <td>{{ obj.hostname }}</td>
                                        <td>{{ obj.ip }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
         </div>
    </div>
{% endblock %}